# =====================================================
# application.properties — Rocketto
# =====================================================

# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/moon-rocket
spring.datasource.username=postgres
spring.datasource.password=*flordemaio2020
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (opcional, padrão 8080)
server.port=8080

nasa.api.key=xFgt74l74UTYtrS5whbLf8RVHfxzcRhAMrn9WOZI